/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as QuantRouteImport } from './routes/quant'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBinanceTradesRouteImport } from './routes/api/binance/trades'
import { Route as ApiBinanceTickerRouteImport } from './routes/api/binance/ticker'
import { Route as ApiBinanceKlinesRouteImport } from './routes/api/binance/klines'
import { Route as ApiBinanceDepthRouteImport } from './routes/api/binance/depth'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantRoute = QuantRouteImport.update({
  id: '/quant',
  path: '/quant',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBinanceTradesRoute = ApiBinanceTradesRouteImport.update({
  id: '/api/binance/trades',
  path: '/api/binance/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBinanceTickerRoute = ApiBinanceTickerRouteImport.update({
  id: '/api/binance/ticker',
  path: '/api/binance/ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBinanceKlinesRoute = ApiBinanceKlinesRouteImport.update({
  id: '/api/binance/klines',
  path: '/api/binance/klines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBinanceDepthRoute = ApiBinanceDepthRouteImport.update({
  id: '/api/binance/depth',
  path: '/api/binance/depth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/quant': typeof QuantRoute
  '/report': typeof ReportRoute
  '/api/binance/depth': typeof ApiBinanceDepthRoute
  '/api/binance/klines': typeof ApiBinanceKlinesRoute
  '/api/binance/ticker': typeof ApiBinanceTickerRoute
  '/api/binance/trades': typeof ApiBinanceTradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/quant': typeof QuantRoute
  '/report': typeof ReportRoute
  '/api/binance/depth': typeof ApiBinanceDepthRoute
  '/api/binance/klines': typeof ApiBinanceKlinesRoute
  '/api/binance/ticker': typeof ApiBinanceTickerRoute
  '/api/binance/trades': typeof ApiBinanceTradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/backtest': typeof BacktestRoute
  '/compare': typeof CompareRoute
  '/quant': typeof QuantRoute
  '/report': typeof ReportRoute
  '/api/binance/depth': typeof ApiBinanceDepthRoute
  '/api/binance/klines': typeof ApiBinanceKlinesRoute
  '/api/binance/ticker': typeof ApiBinanceTickerRoute
  '/api/binance/trades': typeof ApiBinanceTradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/backtest'
    | '/compare'
    | '/quant'
    | '/report'
    | '/api/binance/depth'
    | '/api/binance/klines'
    | '/api/binance/ticker'
    | '/api/binance/trades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/backtest'
    | '/compare'
    | '/quant'
    | '/report'
    | '/api/binance/depth'
    | '/api/binance/klines'
    | '/api/binance/ticker'
    | '/api/binance/trades'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/backtest'
    | '/compare'
    | '/quant'
    | '/report'
    | '/api/binance/depth'
    | '/api/binance/klines'
    | '/api/binance/ticker'
    | '/api/binance/trades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BacktestRoute: typeof BacktestRoute
  CompareRoute: typeof CompareRoute
  QuantRoute: typeof QuantRoute
  ReportRoute: typeof ReportRoute
  ApiBinanceDepthRoute: typeof ApiBinanceDepthRoute
  ApiBinanceKlinesRoute: typeof ApiBinanceKlinesRoute
  ApiBinanceTickerRoute: typeof ApiBinanceTickerRoute
  ApiBinanceTradesRoute: typeof ApiBinanceTradesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quant': {
      id: '/quant'
      path: '/quant'
      fullPath: '/quant'
      preLoaderRoute: typeof QuantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/binance/trades': {
      id: '/api/binance/trades'
      path: '/api/binance/trades'
      fullPath: '/api/binance/trades'
      preLoaderRoute: typeof ApiBinanceTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/binance/ticker': {
      id: '/api/binance/ticker'
      path: '/api/binance/ticker'
      fullPath: '/api/binance/ticker'
      preLoaderRoute: typeof ApiBinanceTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/binance/klines': {
      id: '/api/binance/klines'
      path: '/api/binance/klines'
      fullPath: '/api/binance/klines'
      preLoaderRoute: typeof ApiBinanceKlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/binance/depth': {
      id: '/api/binance/depth'
      path: '/api/binance/depth'
      fullPath: '/api/binance/depth'
      preLoaderRoute: typeof ApiBinanceDepthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BacktestRoute: BacktestRoute,
  CompareRoute: CompareRoute,
  QuantRoute: QuantRoute,
  ReportRoute: ReportRoute,
  ApiBinanceDepthRoute: ApiBinanceDepthRoute,
  ApiBinanceKlinesRoute: ApiBinanceKlinesRoute,
  ApiBinanceTickerRoute: ApiBinanceTickerRoute,
  ApiBinanceTradesRoute: ApiBinanceTradesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
